# Generated by Django 3.2.8 on 2021-11-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anoucments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anoucments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255)),
                ('short', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255)),
                ('short', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faculties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('nip', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(db_column='PASSWORD', max_length=255)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('address', models.CharField(max_length=255)),
                ('private_email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('profile', models.CharField(db_column='PROFILE', max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lecturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=255)),
                ('dates', models.DateField()),
                ('times', models.TimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramStudy',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255)),
                ('short', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'program_study',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dates', models.DateField()),
                ('times', models.TimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('nim', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('address', models.CharField(max_length=255)),
                ('private_email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('profile', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'thesis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThesisCordinator',
            fields=[
                ('idthesis', models.OneToOneField(db_column='idThesis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manta.thesis')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'thesis_cordinator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThesisExaminer',
            fields=[
                ('idthesis', models.OneToOneField(db_column='idThesis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manta.thesis')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'thesis_examiner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThesisTutor',
            fields=[
                ('idthesis', models.OneToOneField(db_column='idThesis', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manta.thesis')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'thesis_tutor',
                'managed': False,
            },
        ),
    ]
