USE manta_db;

CREATE TABLE students(
	nim VARCHAR(50) PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	gender CHAR(1) DEFAULT 'L',
	address VARCHAR(255) NOT NULL,
	private_email VARCHAR(255) NOT NULL,
	mobile VARCHAR(255) NOT NULL,
	PROFILE VARCHAR(255) NOT NULL,
	birth_date DATE,
	birth_place VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE lecturer (
	nip VARCHAR(50) PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	gender CHAR(1) DEFAULT 'L',
	address VARCHAR(255) NOT NULL,
	private_email VARCHAR(255) NOT NULL,
	mobile VARCHAR(255) NOT NULL,
	PROFILE VARCHAR(255) NOT NULL,
	birth_date DATE,
	birth_place VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE faculties(
	id BIGINT(20) PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	short VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE program_study(
	id BIGINT(20) PRIMARY KEY,
	idFaculty BIGINT(20),
	NAME VARCHAR(255) NOT NULL,
	short VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE program_study ADD CONSTRAINT FK_PROGRAM_STUDY_FACULTY 
	FOREIGN KEY (idFaculty) REFERENCES faculties(id);

CREATE TABLE class(
	id BIGINT(20) PRIMARY KEY,
	idProgramStudy BIGINT(20),
	NAME VARCHAR(255) NOT NULL,
	short VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE class ADD CONSTRAINT FK_CLASS_PROGRAM_STUDY
	FOREIGN KEY (idProgramStudy) REFERENCES program_study(id);


CREATE TABLE thesis(
	id BIGINT(20) PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE thesis_tutor (
	idThesis BIGINT(20),
	nip VARCHAR(50),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_THESIS_TUTOR PRIMARY KEY (idThesis, nip)
);
CREATE TABLE thesis_cordinator (
	idThesis BIGINT(20),
	nip VARCHAR(50),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_THESIS_CORDINATOR PRIMARY KEY (idThesis, nip)
);
CREATE TABLE thesis_examiner (
	idThesis BIGINT(20),
	nip VARCHAR(50),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_THESIS_EXAMINER PRIMARY KEY (idThesis, nip)
);

ALTER TABLE thesis_tutor ADD CONSTRAINT FK_THESIS_TUTOR 
	FOREIGN KEY (idThesis) REFERENCES thesis(id);
	
ALTER TABLE thesis_examiner ADD CONSTRAINT FK_THESIS_EXAMINER 
	FOREIGN KEY (idThesis) REFERENCES thesis(id);
	
ALTER TABLE thesis_cordinator ADD CONSTRAINT FK_THESIS_CORDINATOR
	FOREIGN KEY (idThesis) REFERENCES thesis(id);
	
ALTER TABLE thesis_tutor ADD CONSTRAINT FK_TUTOR_THESIS
	FOREIGN KEY (nip) REFERENCES lecturer(nip);

ALTER TABLE thesis_examiner ADD CONSTRAINT FK_EXAMINER_THESIS
	FOREIGN KEY (nip) REFERENCES lecturer(nip);

ALTER TABLE thesis_cordinator ADD CONSTRAINT FK_CORDINATOR_THESIS
	FOREIGN KEY (nip) REFERENCES lecturer(nip);
	
CREATE TABLE anoucments(
	id BIGINT(20) PRIMARY KEY,
	idThesis BIGINT(20),
	title VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE anoucments ADD CONSTRAINT FK_ANNOUCMENT_THESIS 
	FOREIGN KEY (idThesis) REFERENCES thesis(id);
CREATE TABLE meeting(
	id BIGINT(20) PRIMARY KEY,
	idThesis BIGINT(20),
	title VARCHAR(255) NOT NULL,
	description TEXT,
	link VARCHAR(255) NOT NULL,
	dates DATE NOT NULL,
	times TIME NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE meeting ADD CONSTRAINT FK_MEETING_THESIS 
	FOREIGN KEY (idThesis) REFERENCES thesis(id);

CREATE TABLE SCHEDULE(
	id BIGINT(20) PRIMARY KEY,
	idThesis BIGINT(20),
	title VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,
	dates DATE NOT NULL,
	times TIME NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE SCHEDULE ADD CONSTRAINT FK_SCHEDULE_THESIS 
	FOREIGN KEY (idThesis) REFERENCES thesis(id);



